### ISSUE TITLE
cmp-digraphs: special char are not included in search

### ISSUE THREAD

**Issue by mirsella** [Saghen/blink.compat#7]
hello !

[Screencast_20241104_095012.webm](https://github.com/user-attachments/assets/b3303524-6ad7-4f21-86b0-d662998305f3)

as you can see in the record, it seems that the search stop when a special char is used (ie ", ', (, !, etc) which are used to form the digraphs.

Another example, to create ª by `-a`, i first type the - and nothing is sorted (the - is not used to fuzzy search) and then i type the a, and the sort is done with digraphs containing a, but its the same as if the -  wasn't there. furthermore when acceping the completion my manually selecting in from the menu, the a is replaced by the ª, but the - is still here, as it wasn't included in blink sort

also, the source in the completion menu is "unknown" instead of Text or Digraphs, but i don't know which side is this issue

thanks !

**Comment by mirsella** [comment]
also while im here, it seems the prefix `.` defined by the plugin is "useless" as even without it the digraphs completion are shown.
if using the prefix only the digraphs are shown.
this might be a problem with the plugin itself though

**Comment by stefanboca** [comment]
> the search stop when a special char is used (ie ", ', (, !, etc)

This isn't really something I can fix here, because `blink.cmp` doesn't trigger on a per-source regex (what nvim-cmp calls a `keyword_pattern`). Maybe @Saghen can propose a solution? For now, a workaround is to type the `!a` rather than `a!`, then select the correct digraph from the menu (it should be fairly high up due to the fuzzy matching).

> i first type the - and nothing is sorted (the - is not used to fuzzy search)

Again, I can't do much about sorting here.

> when acceping the completion my manually selecting in from the menu, the a is replaced by the ª, but the - is still here

This sould be fixed soon by https://github.com/Saghen/blink.compat/pull/8

> also, the source in the completion menu is "unknown" instead of Text or Digraphs, but i don't know which side is this issue

See https://github.com/Saghen/blink.compat/issues/2#issuecomment-2455538651

> it seems the prefix . defined by the plugin is "useless" as even without it the digraphs completion are shown.

This is the same behavior as in `nvim-cmp`. The `.` is not a prefix, but rather the first character of some digraphs (such as in the digraph `.M`).

**Comment by mirsella** [comment]
thanks !
here is my total config for people stumbling here:
```lua
digraphs = {
  name = "digraphs",
  module = "blink.compat.source",
  override = {
    get_trigger_characters = function()
      return { "." }
    end,
  },
  transform_items = function(ctx, items)
    local kind = require("blink.cmp.types").CompletionItemKind.Text
    for i, _ in ipairs(items) do
      items[i].kind = kind
    end
    return items
  end,
  score_offset = -10,
},

```
